# SPDX-License-Identifier: GPL-3.0-or-later
# Weekly update PRs for the GitHub Actions, which the release workflow pins by commit SHA.
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
